services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: docker
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=2000
    ports:
      - 5432:5432
  
  auth_service:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: 
      - .env
    ports:
      - 8080:8080

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["alembic"]
    command: ["upgrade", "head"]
    depends_on:
      - postgres
    env_file:
      - .env
