"""remove token field

Revision ID: 6d69f78ca0d4
Revises: 52bd34446076
Create Date: 2024-11-29 22:46:26.519269

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d69f78ca0d4"
down_revision: Union[str, None] = "52bd34446076"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
